name: mastodon_entities
description: This package provides classes for working with Mastodon API entities in Dart.
version: 1.1.15
repository: https://github.com/MahanRahmati/mastodon-entities
topics:
  - mastodon
  - entities

environment:
   sdk: ^3.10.1

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
